name: Spell Check

on:
  push:

jobs:
  spellcheck:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install

      - name: Run cspell
        run: deno run -A npm:cspell@8.19.4 "**/*"
